<?php
/**
 * @file
 * Code for the Ignition Sites feature.
 */

include_once('ignition_sites.features.inc');

/**
 * Implementation of hook_services_resources().
 */
function ignition_sites_services_resources() {
  $resources['ignition-site'] = array(
    'index' => array(
      'help' => 'Retrieves a list of Ignition managed sites.',
      'file' => array(
        'file' => 'inc',
        'module' => 'ignition_sites'
      ),
      'callback' => '_ignition_sites_services_index_sites',
      // TODO: We'll need our own access system.
      'access callback' => 'ignition_sites_site_services_access',
      'access arguments' => array('access content'),
      //'access arguments append' => FALSE,
      'args' => array(
         array(
           'name' => 'page',
           'type' => 'int',
           'description' => '',
           'source' => array(
             'param' => 'page',
           ),
           'optional' => TRUE,
           'default value' => 0,
         ),
        array(
           'name' => 'name',
           'type' => 'string',
           'description' => 'The machine name of the site to get',
           'source' => array(
             'param' => 'name',
           ),
           'optional' => TRUE,
           'default value' => '',
        ),
      ),
    ),
    'retrieve' => array(
      'help' => 'Retrieves a signle Ignition managed site.',
      'file' => array(
        'file' => 'inc',
        'module' => 'ignition_sites'
      ),
      'callback' => '_ignition_sites_services_retrieve_site',
      // TODO: We'll need our own access system.
      'access callback' => 'ignition_sites_site_services_access',
      //'access arguments' => array('access content'),
      //'access arguments append' => FALSE,
      'args' => array(
         array(
           'name' => 'name',
           'type' => 'string',
           'description' => 'The machine name of the site to get',
           'source' => array('path' => '0'),
           'optional' => FALSE,
         ),
     ),
    ),
  );
  return $resources;
}

function ignition_sites_site_services_access() {
  return TRUE;
}

